/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab8p2_diegocasco;

import java.awt.Color;
import java.util.ArrayList;
import java.util.Random;
import javax.swing.DefaultListModel;
import javax.swing.JColorChooser;
import javax.swing.JOptionPane;
import javax.swing.JProgressBar;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dcasc
 */
public class Main extends javax.swing.JFrame implements Runnable{
  Random r=new Random();
    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        Item i = new Item();
        textarea.setEditable(false);
    }
    Jugador j =new Jugador();
    private JProgressBar barra;
    private boolean avanzar;
    Thread hilo = new Thread();

    public void run() {
        while (avanzar) {
            if (avanzar) {
                barra.setValue(0);
            } //FIN IF

            try {
                Thread.sleep(0);
            } catch (InterruptedException ex) {
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jProgressBar1 = new javax.swing.JProgressBar();
        jPanel3 = new javax.swing.JPanel();
        tf_comandos = new javax.swing.JTextField();
        Jb_comands = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        textarea = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tf_nombremascot = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tf_puntosvida = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tf_delay = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tf_costo = new javax.swing.JTextField();
        JB_color = new javax.swing.JButton();
        JB_CrearMascota = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        tf_nomitems = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        CB_alimento = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        tf_probObtener = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tf_precio = new javax.swing.JTextField();
        JB_crearitem = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tf_nombre = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        itemszona = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        listitems = new javax.swing.JList<>();
        jLabel12 = new javax.swing.JLabel();
        tf_probderumbe = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        tf_probataque = new javax.swing.JTextField();
        jb_items = new javax.swing.JButton();
        jb_zona = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Delay", "Costo", "Color", "Puntos de vida"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 753, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 351, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Mascotas", jPanel1);

        tf_comandos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tf_comandosKeyPressed(evt);
            }
        });

        Jb_comands.setText(">");
        Jb_comands.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jb_comandsActionPerformed(evt);
            }
        });

        textarea.setColumns(20);
        textarea.setRows(5);
        jScrollPane5.setViewportView(textarea);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(tf_comandos, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Jb_comands, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane5))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_comandos)
                    .addComponent(Jb_comands, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Comandos", jPanel3);

        jLabel1.setText("Crear Mascotas");

        jLabel2.setText("Nombre");

        jLabel3.setText("Puntos de Vida");

        tf_puntosvida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_puntosvidaActionPerformed(evt);
            }
        });

        jLabel4.setText("Delay");

        jLabel5.setText("Costo");

        JB_color.setText("Color");
        JB_color.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_colorActionPerformed(evt);
            }
        });

        JB_CrearMascota.setText("Crear Mascota");
        JB_CrearMascota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_CrearMascotaActionPerformed(evt);
            }
        });

        jLabel6.setText("Crear Items");

        jLabel7.setText("Nombre");

        CB_alimento.setText("Alimento");

        jLabel8.setText("Probabilidad de Obtencion");

        jLabel9.setText("Precio");

        JB_crearitem.setText("Crear Item");
        JB_crearitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_crearitemActionPerformed(evt);
            }
        });

        jLabel10.setText("Crear Zona");

        jLabel11.setText("Nombre");

        itemszona.setModel(new DefaultListModel());
        jScrollPane2.setViewportView(itemszona);

        listitems.setModel(new DefaultListModel());
        jScrollPane3.setViewportView(listitems);

        jLabel12.setText("Probabilidad de Derrumbe");

        jLabel13.setText("Probabilidad de Ataque");

        jb_items.setText("Agregar Items");
        jb_items.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_itemsActionPerformed(evt);
            }
        });

        jb_zona.setText("Crear Zona");
        jb_zona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_zonaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(16, 16, 16)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(52, 52, 52))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(tf_delay, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(tf_costo, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(JB_CrearMascota, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(JB_color, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(tf_puntosvida, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(39, 39, 39))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tf_nombremascot, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_probObtener, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_nomitems)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CB_alimento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tf_precio)
                            .addComponent(JB_crearitem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(24, 24, 24)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tf_nombre)
                                            .addComponent(tf_probderumbe)
                                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(tf_probataque))
                                                .addGap(1, 1, 1)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(92, 92, 92))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jb_items, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                                    .addComponent(jb_zona, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6)
                    .addComponent(jLabel10))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tf_nombremascot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tf_nomitems, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(tf_puntosvida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tf_probderumbe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(28, 28, 28)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel12)
                                            .addComponent(CB_alimento))))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel13))
                                .addGap(12, 12, 12)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tf_delay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tf_probObtener, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel5))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(tf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(101, 101, 101)
                                        .addComponent(tf_probataque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(tf_costo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel9))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tf_precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(JB_color, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(JB_crearitem))
                                .addGap(26, 26, 26)
                                .addComponent(JB_CrearMascota, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jb_items)
                                .addGap(34, 34, 34)
                                .addComponent(jb_zona))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(226, 226, 226)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Admistrador", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_puntosvidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_puntosvidaActionPerformed
        // TODO add your handling code here:  
    }//GEN-LAST:event_tf_puntosvidaActionPerformed

    private void JB_colorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_colorActionPerformed
        // TODO add your handling code here:
        JB_color.setBackground(
                JColorChooser.showDialog(
                        this, "Seleccione un color",
                        Color.yellow)
        );
    }//GEN-LAST:event_JB_colorActionPerformed

    private void JB_CrearMascotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_CrearMascotaActionPerformed
        // TODO add your handling code here:
        AdminMascotas am= new AdminMascotas("./mascotas.cdc");
        mascotas.add(new Mascotas(tf_nombremascot.getText(), Integer.parseInt(tf_puntosvida.getText()), Integer.parseInt(tf_delay.getText()), Integer.parseInt(tf_costo.getText()), JB_color.getBackground()));
        tf_nombremascot.setText("");
        tf_puntosvida.setText("");
        tf_delay.setText("");
        tf_costo.setText("");
        JB_color.setBackground(Color.LIGHT_GRAY);
        am.escribirArchivo();
    }//GEN-LAST:event_JB_CrearMascotaActionPerformed

    private void JB_crearitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_crearitemActionPerformed
        AdminItems ai = new AdminItems("./items.cdc");
        ai.cargarArchivo();
            if (CB_alimento.isSelected()) {
                DefaultListModel modelo = (DefaultListModel) listitems.getModel();
                modelo.addElement(new Item(0, tf_nomitems.getText(), true, Integer.parseInt(tf_probObtener.getText()), Integer.parseInt(tf_precio.getText())));
                tf_nomitems.setText("");
                tf_probObtener.setText("");
                tf_precio.setText("");
                ai.escribirArchivo();
            } else {
                DefaultListModel modelo = (DefaultListModel) listitems.getModel();
                modelo.addElement(new Item(0, tf_nomitems.getText(), false, Integer.parseInt(tf_probObtener.getText()), Integer.parseInt(tf_precio.getText())));
                tf_nomitems.setText("");
                tf_probObtener.setText("");
                tf_precio.setText("");
                ai.escribirArchivo();
            }
    }//GEN-LAST:event_JB_crearitemActionPerformed

    private void jb_itemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_itemsActionPerformed
        // TODO add your handling code here:
        DefaultListModel modelolista = (DefaultListModel)itemszona.getModel();
        DefaultListModel modelolistaItem = (DefaultListModel)listitems.getModel();
        modelolista.addElement(modelolistaItem.getElementAt(listitems.getSelectedIndex()));
    }//GEN-LAST:event_jb_itemsActionPerformed

    private void Jb_comandsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jb_comandsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jb_comandsActionPerformed
    
    private void cargartabla(){
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {},
            new String [] {
                "Nombre", "Delay", "Costo", "Color", "Puntos de vida"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
            boolean[] canEdit = new boolean[]{
                        false, false,false,false,false
                    };
        });
    }
    
    private void tf_comandosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_comandosKeyPressed

        if(evt.getKeyCode()== 10){
          String comandos[]=tf_comandos.getText().split(" ");
          if(comandos[0].equals("!pet")){
              if(comandos[1].equals("list")){
                  tf_comandos.setText("");
                  textarea.append("********lista mascotas********\n");
                  for (Mascotas mascota : mascotas) {
                      textarea.append(mascota.getNombre()+"\n");
                  }
                  textarea.append("********************\n");
              }if(comandos[1].equals("feed")){
                  for (Item item : items) {
                  if(comandos[2].equals(item.getId())&& item.isAlimento()==true){
                      j.getItems().remove(item);
                  }
              }
              }
              if (comandos[1].equals("active")) {
                  for (Mascotas mascota : mascotas) {
                      if (comandos[2].equals(mascota.getNombre())) {
                          cargartabla();
                          Object[] newrow = {
                              mascota.getNombre(),
                              mascota.getDelay(),
                              mascota.getCosto(),
                              mascota.getColor(),
                              mascota.getPuntosvida()
                          };
                          DefaultTableModel mascotat
                                  = (DefaultTableModel) jTable1.getModel();
                          mascotat.addRow(newrow);
                          jTable1.setModel(mascotat);
                      }
                  }
              }
          }if(comandos[0].equals("!mine")){
              for (Zona zona : zonas) {
                  if(comandos[1].equals(zona.getId())){
                    int random =1+r.nextInt(100);
                    if(random>= zona.getProbderrumbe()){
                        j.setDinero(0);
                    }else{
                        int random2 =1+r.nextInt(500);
                        int dinero= j.getDinero()+random2;
                        j.setDinero(dinero);
                    }
                  }
            }
          }if(comandos[0].equals("!fish")){
              for (Zona zona : zonas) {
                  if(comandos[1].equals(zona.getId())){
                    int random =1+r.nextInt(100);
                    if(random>= zona.getProbataque()){
                        j.setDinero(0);
                    }else{
                        int random2 =1+r.nextInt(500);
                        int dinero= j.getDinero()+random2;
                        j.setDinero(dinero);
                    }
                  }
          }if(comandos[0].equals("!zone")){
              if(comandos[1].equals("list")){
                  textarea.append("********Lista Zonas********\n");
                  for (Zona zona : zonas) {
                      textarea.append(zona.getNombre());
                  }
                  textarea.append("*****************\n");
              }
          }if(comandos[0].equals("!adopt")){
              for (Mascotas mascota : mascotas) {
                if(comandos[1].equals(mascota.getNombre())&& j.getDinero()>= mascota.getCosto()){
                    j.getMascot().add(mascota);
                    textarea.append("Has adoptado a la mascota: "+mascota.getNombre());
                }else{
                    textarea.append("no tiene Dinero\n");
                }
            }
              
          }if(comandos[0].equals("!item")){
              if(comandos[1].equals("list")){
                  textarea.append("**********List Items*********\n");
                  for (Item item : items) {
                      textarea.append(item.getNombre());
                  }
                  textarea.append("******************");
              }
          }if(comandos[0].equals("!buy")){
              for (Item item : items) {
                if(comandos[1].equals(item.getId())&&j.getDinero()>=item.getPrecioventa()){
                    int dinero=j.getDinero()-item.getPrecioventa();
                    j.setDinero(dinero);
                    j.getItems().add(item);
                }else{
                    textarea.append("No tiene dinero\n");
                }
            }
          }if(comandos[0].equals("!bag")){
              for(int i=0;i<j.getItems().size();i++){
                  textarea.append(j.getItems().toString());
              }                  
          }if(comandos[0].equals("!d")){
              j.setDinerobank(Integer.parseInt(comandos[1]));
              j.setDinero(j.getDinero()-Integer.parseInt(comandos[1]));
          }if(comandos[0].equals("!w")){
              j.setDinero(Integer.parseInt(comandos[1]));
              j.setDinero(j.getDinerobank()-Integer.parseInt(comandos[1]));
          }if(comandos[0].equals("!b")){
              textarea.append("Su dinero en persoan : "+ j.getDinero()+"\n");
              textarea.append("su dinero en el banco es de : "+j.getDinerobank()+"\n");
          }if(comandos[0].equals("!clear")){
              textarea.removeAll();
          }if(comandos[0].equals("!sell")){
              for (Item item : items) {
                if(comandos[1].equals(item.getId())&&j.getItems().equals(item.getId())){
                    j.getItems().remove(item);
                    j.setDinero(j.getDinero()+item.getPrecioventa());
            }else{
                    textarea.append("No tiene el item\n");
                }
            }    
          }
        }
        }  
    }//GEN-LAST:event_tf_comandosKeyPressed

    private void jb_zonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_zonaActionPerformed
        // TODO add your handling code here:
        AdminZona az=new AdminZona("./zona.cdc");
        zonas.add(new Zona(zonas.size()-1,tf_nombre.getText(),Integer.parseInt(tf_probderumbe.getText()),Integer.parseInt(tf_probataque.getText())));
        ///for(int i=0;i< itemszona.getSize();i++){
           //zonas.get(zonas.size()-1).getItems().add(e); 
        //}
        az.escribirArchivo();
    }//GEN-LAST:event_jb_zonaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CB_alimento;
    private javax.swing.JButton JB_CrearMascota;
    private javax.swing.JButton JB_color;
    private javax.swing.JButton JB_crearitem;
    private javax.swing.JButton Jb_comands;
    private javax.swing.JList<String> itemszona;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jb_items;
    private javax.swing.JButton jb_zona;
    private javax.swing.JList<String> listitems;
    private javax.swing.JTextArea textarea;
    private javax.swing.JTextField tf_comandos;
    private javax.swing.JTextField tf_costo;
    private javax.swing.JTextField tf_delay;
    private javax.swing.JTextField tf_nombre;
    private javax.swing.JTextField tf_nombremascot;
    private javax.swing.JTextField tf_nomitems;
    private javax.swing.JTextField tf_precio;
    private javax.swing.JTextField tf_probObtener;
    private javax.swing.JTextField tf_probataque;
    private javax.swing.JTextField tf_probderumbe;
    private javax.swing.JTextField tf_puntosvida;
    // End of variables declaration//GEN-END:variables
    ArrayList <Zona> zonas=new ArrayList();
    ArrayList <Mascotas> mascotas = new ArrayList();
    ArrayList <Item> items= new ArrayList();
}
